services:
  eclipse-mosquitto:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto:latest
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - ${DOCKER_MQTT_BROKER_PORT}:1883
      - ${DOCKER_MQTT_WEBSOCKET_PORT}:9001
    volumes:
      - ${DOCKER_MQTT_VOLUME}/config/${DOCKER_MQTT_CONFIGFILE}:/mosquitto/config/mosquitto.conf
      - ${DOCKER_MQTT_VOLUME}/data:/mosquitto/data
      - ${DOCKER_MQTT_VOLUME}/log:/mosquitto/log
    
  influxdb2:
    container_name: influxdb2
    image: influxdb:latest
    env_file:
      - ./.env
    depends_on:
      eclipse-mosquitto:
        condition: service_started
    restart: unless-stopped
    ports:
      - ${DOCKER_INFLUXDB_PORT}:8086
    volumes:
      - ${DOCKER_INFLUXDB_VOLUME}/data:/var/lib/influxdb2
      - ${DOCKER_INFLUXDB_VOLUME}/config:/etc/influxdb2
      
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    env_file:
      - ./.env
    depends_on:
      influxdb2:
        condition: service_started
      eclipse-mosquitto:
        condition: service_started
    restart: unless-stopped  
    volumes:
      - ${DOCKER_TELEGRAF_VOLUME}/config/${DOCKER_TELEGRAF_CONFIGFILE}:/etc/telegraf/telegraf.conf:ro
    
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    env_file:
      - ./.env
    depends_on:
      influxdb2:
        condition: service_started
    restart: unless-stopped
    ports:
      - ${DOCKER_GRAFANA_PORT}:3000
    volumes:
      - ${DOCKER_GRAFANA_VOLUME}/data:/var/lib/grafana
      - ./certs:${GF_CERT_PATH}:ro

